### ISSUE TITLE
Error in bongo-mplayer-available-drivers for non-english locales

### ISSUE THREAD

**Issue by EugineKosenko** [dbrock/bongo#10]
The function expects the answer "Available audio output drivers:" from the MPlayer, but when the current locale is not English, the function is failed. It is actual to force the standard English locale here, for example, in the next way:

<pre>
(let ((process-environment (cons "LANG=en_US.UTF-8" process-environment)))
  (call-process bongo-mplayer-program-name nil t nil
	(ecase type
	  (audio "-ao")
	  (video "-vo"))
	"help"))
</pre>

**Comment by dbrock** [comment]
Good idea. However, it may be better to use `LC_ALL=C`, rather than `LANG=en_US.UTF-8`.

The `C` locale is a standard locale available everywhere and is a good fit for machine-parsing of output. The `LC_ALL` variable, if present, overrides `LANG` and all other locale settings.

Would you like to make a pull request?

**Comment by EugineKosenko** [comment]
I made one, but I'm newbie here. I hope I did it properly.
