### ISSUE TITLE
VLC backend never fetches timing data

### ISSUE THREAD

**Issue by iqbalansari** [dbrock/bongo#25]
It seems that the code that triggers `bongo-vlc-player-start-timer` in `bongo-vlc-process-filter` is never run, most probably because the [patterns](https://github.com/dbrock/bongo/blob/0ee957db9abe410eae0b5fb55959437980509aac/bongo.el#L5843-L5850) it looks for running `bongo-vlc-player-start-timer` are not emitted by the backend vlc process anymore

**Comment by thwg** [comment]
I'm also seeing this behavior with (VLC 2.2.0-rc2, from Debian stable).  It looks like the `status` command should be periodically sent to poll the current state with the new RC, as it does not automatically print it.

State is also now indicated with a name instead of an integer, e.g
```
( new input: file:///home/shw/Music/Little Boots - Hands - 04 - Click.mp3 )
( audio volume: 38 )
( state paused )
```

[New RC format](https://github.com/videolan/vlc/blob/9053b0919f00d88f16e1ef3e3f79b1cced74f742/share/lua/intf/cli.lua#L401-L408). [Old RC format](https://github.com/videolan/vlc/blob/9053b0919f00d88f16e1ef3e3f79b1cced74f742/modules/control/oldrc.c#L851-L884).  The [switch](https://github.com/videolan/vlc/commit/a2110274cbd5f91053b094cd9f0b3b8fa90e9ae1) appeared to be somewhere in March.

Until the new RC format is supported, customizing `bongo-vlc-extra-arguments` to include `-I oldrc` works for me after manually seeking.  I'll submit a PR to suggest it as the default and fix it so that it does not require the manual seek.

**Comment by iqbalansari** [comment]
@thwg great work figuring this out. I just tried your patch and it seems to work well, I will try it on an older VLC version today and report back

**Comment by thwg** [comment]
Awesome, will look forward to the details.

After testing a bit more, I believe the placement of [this line](https://github.com/videolan/vlc/blob/9053b0919f00d88f16e1ef3e3f79b1cced74f742/modules/control/oldrc.c#L510) is the culprit causing the requirement of performing an action before getting the state information and starting `bongo-vlc-player-start-timer'.

It requires a single command to be read before initially sending the state information.  Sending a blank newline after startup seems to work, and doesn't require the "audio volume" hack used in my PR (which is always printed at startup).  It might be a cleaner approach.

As for detecting different VLC versions, if necessary, perhaps running a separate process beforehand (`vlc --version`) and determining whether to use 'rc' or 'oldrc' would be a good approach?

I'll have some time on Sunday evening to work on this a bit more.

**Comment by iqbalansari** [comment]
Looking at [NEWS](https://github.com/videolan/vlc/blob/290ebe50e0d2319a17759e1d4eae6e4368687d4c/NEWS#L2185) it seems that oldrc was introduced in version [1.1.0](https://github.com/videolan/vlc/blob/290ebe50e0d2319a17759e1d4eae6e4368687d4c/NEWS#L2074) (which was five years ago). Don't know about other distros but 12.04 is the oldest [LTS version for Ubuntu](https://wiki.ubuntu.com/LTS) and it ships with VLC v2.0.8, as such I think VLC version check might not be required.

**Comment by iqbalansari** [comment]
BTW it worked well on v2.0.8 of VLC.

> Sending a blank newline after startup seems to work, and doesn't require the "audio volume" hack used in my PR (which is always printed at startup). It might be a cleaner approach.

It would be great if it works without user interaction.

**Comment by thwg** [comment]
Thanks for the info; looks like it has been around longer than I thought!  I agree, there probably isn't any need to differentiate between versions.

Here is a [different patch](https://github.com/thwg/bongo/commit/a097a92ab74a1817cbf5562167185821befdc5ac) which relies on the output of the VLC initialization message.  I think it's a better patch seeing as that header is consistently there and only runs once, whereas I'm not sure the "audio volume" necessarily has to be.  It should work at least through 2.0.8 (Ubuntu 12.04) and 2.2.1 (Ubuntu 15.10).

It involves moving the timer start out of the play case, but seeing as `--play-and-exit` was added to the command in 2009, that may be a vestigial case -- I don't think that it should affect anything negatively by moving it outside.

Let me know if it also works well for you, and if so, I'll propose this instead of the previous PR.  Thanks!

**Comment by iqbalansari** [comment]
Just tested it and seems to work well, great work :+1: , thanks!

**Comment by dbrock** [comment]
Great work researching this. Thanks a lot!
