### ISSUE TITLE
Minimum Emacs version supported

### ISSUE THREAD

**Issue by iqbalansari** [dbrock/bongo#29]
I was trying to cleanup Bongo code since emacs lisp byte compiler right now reports a lot of warnings. While doing so there were multiple occurrences of the following warning

>Warning: `interactive-p` is an obsolete function (as of
>    23.2); use `called-interactively-p' instead.

I was wondering what is the minimum version Bongo intends to support, is it okay if I change calls to `interactive-p` to `called-interactively-p` (and break compatibility with Emacs 23.2)?

**Comment by dbrock** [comment]
Thanks for bringing this up. I appreciate the effort to clean up the compilation warnings.

It used to be that we supported GNU Emacs all the way back to version 21.1, but that code was moved into a separate file many years ago and subsequently dropped altogether. Since then, I believe 22.1 is the oldest version we've been supporting. But seeing as how that's now almost a decade old, I think we can safely bump the minimum version up to at least 23.4 (released in January 2012, nearly four years ago).

So I say go ahead and change those calls.

Let me know if you run into anything else like this. I wouldn't mind restricting support even further if necessary.

**Comment by iqbalansari** [comment]
Thanks for your clarification. I will work on it, this weekend. Looking at [Emacs release history)[https://www.gnu.org/software/emacs/history.html], Emacs v24.1 and Emacs v23.4 were separated by just 4 months. I would suggest we drop compatibility for Emacs v23, your thoughts?

**Comment by zobi8225** [comment]
agree.

-- 
Thomas Luquet
mail : thomas@luquet.net

**Comment by dbrock** [comment]
Fine by me.
